# =================================
# Settings for the baseline method.
#
# author: Konstantinos Drossos
# affiliation: Tampere University
# =================================
model: !include model_baseline.yaml
# -----------------------------------
data:
  input_field_name: 'features'
  output_field_name: 'words_ind'
  load_into_memory: No
  batch_size: 16
  shuffle: Yes
  num_workers: 4
  drop_last: Yes
# -----------------------------------
training:
  nb_epochs: 300
  patience: 10
  loss_thr: !!float 1e-4
  optimizer:
    lr: !!float 1e-4
  grad_norm:
    value: !!float 1.  # Set value to -1 for not using gradient clipping
    norm: 2
  force_cpu: No
  text_output_every_nb_epochs: !!int 10
  nb_examples_to_sample: 100
# EOF
